# coding: utf-8

"""
    UbiOps

    Client Library to interact with the UbiOps API.  # noqa: E501

    The version of the OpenAPI document: v2.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ubiops.configuration import Configuration


class ProjectUpdate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'advanced_permissions': 'bool',
        'gb_seconds': 'int',
        'suspend': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'advanced_permissions': 'advanced_permissions',
        'gb_seconds': 'gb_seconds',
        'suspend': 'suspend'
    }

    def __init__(self, name=None, advanced_permissions=None, gb_seconds=None, suspend=None, local_vars_configuration=None):  # noqa: E501
        """ProjectUpdate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._advanced_permissions = None
        self._gb_seconds = None
        self._suspend = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if advanced_permissions is not None:
            self.advanced_permissions = advanced_permissions
        self.gb_seconds = gb_seconds
        if suspend is not None:
            self.suspend = suspend

    @property
    def name(self):
        """Gets the name of this ProjectUpdate.  # noqa: E501


        :return: The name of this ProjectUpdate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProjectUpdate.


        :param name: The name of this ProjectUpdate.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                name is not None and not isinstance(name, str)):
            raise ValueError("Parameter `name` must be a string")  # noqa: E501

        if (self.local_vars_configuration.client_side_validation and
                name is not None and len(name) < 1):
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def advanced_permissions(self):
        """Gets the advanced_permissions of this ProjectUpdate.  # noqa: E501


        :return: The advanced_permissions of this ProjectUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._advanced_permissions

    @advanced_permissions.setter
    def advanced_permissions(self, advanced_permissions):
        """Sets the advanced_permissions of this ProjectUpdate.


        :param advanced_permissions: The advanced_permissions of this ProjectUpdate.  # noqa: E501
        :type: bool
        """
        if (self.local_vars_configuration.client_side_validation and
                advanced_permissions is not None and not isinstance(advanced_permissions, bool)):
            raise ValueError("Parameter `advanced_permissions` must be a boolean")  # noqa: E501

        self._advanced_permissions = advanced_permissions

    @property
    def gb_seconds(self):
        """Gets the gb_seconds of this ProjectUpdate.  # noqa: E501


        :return: The gb_seconds of this ProjectUpdate.  # noqa: E501
        :rtype: int
        """
        return self._gb_seconds

    @gb_seconds.setter
    def gb_seconds(self, gb_seconds):
        """Sets the gb_seconds of this ProjectUpdate.


        :param gb_seconds: The gb_seconds of this ProjectUpdate.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                gb_seconds is not None and not isinstance(gb_seconds, int)):
            raise ValueError("Parameter `gb_seconds` must be an integer")  # noqa: E501

        self._gb_seconds = gb_seconds

    @property
    def suspend(self):
        """Gets the suspend of this ProjectUpdate.  # noqa: E501


        :return: The suspend of this ProjectUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._suspend

    @suspend.setter
    def suspend(self, suspend):
        """Sets the suspend of this ProjectUpdate.


        :param suspend: The suspend of this ProjectUpdate.  # noqa: E501
        :type: bool
        """
        if (self.local_vars_configuration.client_side_validation and
                suspend is not None and not isinstance(suspend, bool)):
            raise ValueError("Parameter `suspend` must be a boolean")  # noqa: E501

        self._suspend = suspend

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectUpdate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectUpdate):
            return True

        return self.to_dict() != other.to_dict()
