# UbiOps
#
# Client Library to interact with the UbiOps API.
#
# UbiOps API version: v2.1
# Generated by custom generator based on: https://openapi-generator.tech

# Files operations


#' @title Create bucket
#' @description Create a bucket in a project
#' @param data  named list of: [ name, provider, credentials (optional), configuration (optional), ttl (optional), description (optional), labels (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the created bucket
#'   - `id`: Unique identifier for the bucket (UUID)
#'   - `name`: Name of the bucket
#'   - `project`: Project name in which the bucket is created
#'   - `provider`: Provider of the bucket
#'   - `credentials`: Credentials to connect to the bucket
#'   - `configuration`: Additional configuration details for the bucket
#'   - `creation_date`: The date when the bucket was created
#'   - `description`: Description of the bucket
#'   - `labels`: Dictionary containing key/value pairs where key indicates the label and value is the corresponding value of that label
#'   - `ttl`: Time to live for the files in the bucket
#' @examples
#' \dontrun{
#' data <- list(
#'  name = "name",
#'  provider = "provider",  # one of: [ubiops, google_cloud_storage, amazon_s3, azure_blob_storage] 
#'  credentials = list(key = "value"),  # (optional)
#'  configuration = list(key = "value"),  # (optional)
#'  ttl = 0,  # (optional)
#'  description = "description",  # (optional)
#'  labels = list(key = "value")  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::buckets_create(
#'    data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::buckets_create(
#'    data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
buckets_create <- function(data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}/buckets"

  api.response <- call_api(url_path, "POST", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Delete a bucket
#' @description Delete a bucket. If the bucket provider is UbiOps, the files in the bucket will be deleted together with the bucket. For other providers, the files in the bucket are not removed but just the connection from UbiOps to the bucket.
#' @param bucket.name  character
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' ubiops::buckets_delete(
#'    bucket.name
#' )
#' 
#' # Or provide directly
#' ubiops::buckets_delete(
#'    bucket.name,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
buckets_delete <- function(bucket.name,  ...){
  query_params <- list()

  if (missing(`bucket.name`)) {
    stop("Missing required parameter `bucket.name`.")
  }
  
  url_path <- "/projects/{project_name}/buckets/{bucket_name}"
  if (!missing(`bucket.name`)) {
    url_path <- gsub("\\{bucket_name\\}", utils::URLencode(as.character(`bucket.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "DELETE", NULL, query_params, ...)
  return(invisible(NULL))
}


#' @title Get details of a bucket
#' @description Retrieve details of a bucket in a project
#' @param bucket.name  character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of a bucket
#'   - `id`: Unique identifier for the bucket (UUID)
#'   - `name`: Name of the bucket
#'   - `project`: Project name in which the bucket is defined
#'   - `provider`: Provider of the bucket
#'   - `configuration`: Additional configuration details for the bucket
#'   - `creation_date`: The date when the bucket was created
#'   - `description`: Description of the bucket
#'   - `labels`: Dictionary containing key/value pairs where key indicates the label and value is the corresponding value of that label
#'   - `ttl`: Time to live for the files in the bucket
#'   - `size`: Size of the bucket according to the last measurement date
#'   - `size_measurement_date`: Last measurement date of the size of the bucket
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::buckets_get(
#'    bucket.name
#' )
#' 
#' # Or provide directly
#' result <- ubiops::buckets_get(
#'    bucket.name,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
buckets_get <- function(bucket.name,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`bucket.name`)) {
    stop("Missing required parameter `bucket.name`.")
  }
  
  url_path <- "/projects/{project_name}/buckets/{bucket_name}"
  if (!missing(`bucket.name`)) {
    url_path <- gsub("\\{bucket_name\\}", utils::URLencode(as.character(`bucket.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List buckets
#' @description List buckets in a project
#' @param labels (optional) character - Example: "label1:value1,label2:value2"
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list of details of the buckets in the project
#'   - `id`: Unique identifier for the bucket (UUID)
#'   - `name`: Name of the bucket
#'   - `project`: Project name in which the bucket is defined
#'   - `provider`: Provider of the bucket
#'   - `configuration`: Additional configuration details for the bucket
#'   - `creation_date`: The date when the bucket was created
#'   - `description`: Description of the bucket
#'   - `labels`: Dictionary containing key/value pairs where key indicates the label and value is the corresponding value of that label
#'   - `ttl`: Time to live for the files in the bucket
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::buckets_list(
#'    
#'    labels = NULL
#' )
#' 
#' # Or provide directly
#' result <- ubiops::buckets_list(
#'    
#'    labels = NULL, 
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
buckets_list <- function(labels=NULL,  preload_content=TRUE, ...){
  query_params <- list()

  query_params['labels'] <- labels
  
  url_path <- "/projects/{project_name}/buckets"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Update a bucket
#' @description Update a bucket
#' @param bucket.name  character
#' @param data  named list of: [ credentials (optional), configuration (optional), ttl (optional), description (optional), labels (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the updated bucket
#'   - `id`: Unique identifier for the bucket (UUID)
#'   - `name`: Name of the bucket
#'   - `project`: Project name in which the bucket is defined
#'   - `provider`: Provider of the bucket
#'   - `configuration`: Additional configuration details for the bucket
#'   - `creation_date`: The date when the bucket was created
#'   - `description`: Description of the bucket
#'   - `labels`: Dictionary containing key/value pairs where key indicates the label and value is the corresponding value of that label
#'   - `ttl`: Time to live for the files in the bucket
#'   - `size`: Size of the bucket according to the last measurement date
#'   - `size_measurement_date`: Last measurement date of the size of the bucket
#' @examples
#' \dontrun{
#' data <- list(
#'  credentials = list(key = "value"),  # (optional)
#'  configuration = list(key = "value"),  # (optional)
#'  ttl = 0,  # (optional)
#'  description = "description",  # (optional)
#'  labels = list(key = "value")  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::buckets_update(
#'    bucket.name, data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::buckets_update(
#'    bucket.name, data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
buckets_update <- function(bucket.name, data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`bucket.name`)) {
    stop("Missing required parameter `bucket.name`.")
  }
  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}/buckets/{bucket_name}"
  if (!missing(`bucket.name`)) {
    url_path <- gsub("\\{bucket_name\\}", utils::URLencode(as.character(`bucket.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "PATCH", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Delete a file
#' @description Delete a file from a bucket
#' @param bucket.name  character
#' @param file  character
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' ubiops::files_delete(
#'    bucket.name, file
#' )
#' 
#' # Or provide directly
#' ubiops::files_delete(
#'    bucket.name, file,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
files_delete <- function(bucket.name, file,  ...){
  query_params <- list()

  if (missing(`bucket.name`)) {
    stop("Missing required parameter `bucket.name`.")
  }
  if (missing(`file`)) {
    stop("Missing required parameter `file`.")
  }
  
  url_path <- "/projects/{project_name}/buckets/{bucket_name}/files/{file}"
  if (!missing(`bucket.name`)) {
    url_path <- gsub("\\{bucket_name\\}", utils::URLencode(as.character(`bucket.name`), reserved = TRUE), url_path)
  }
  if (!missing(`file`)) {
    url_path <- gsub("\\{file\\}", utils::URLencode(as.character(`file`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "DELETE", NULL, query_params, ...)
  return(invisible(NULL))
}


#' @title Download a file
#' @description Generate a signed url to download a file. Request body should be an empty dictionary.
#' @param bucket.name  character
#' @param file  character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  - `url`: A url which can be used to download the file from bucket. Make a GET request to this url to download the file.
#'   - `provider`: Provider of the bucket where the file will be uploaded
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::files_download(
#'    bucket.name, file
#' )
#' 
#' # Or provide directly
#' result <- ubiops::files_download(
#'    bucket.name, file,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
files_download <- function(bucket.name, file,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`bucket.name`)) {
    stop("Missing required parameter `bucket.name`.")
  }
  if (missing(`file`)) {
    stop("Missing required parameter `file`.")
  }
  
  url_path <- "/projects/{project_name}/buckets/{bucket_name}/files/{file}/download"
  if (!missing(`bucket.name`)) {
    url_path <- gsub("\\{bucket_name\\}", utils::URLencode(as.character(`bucket.name`), reserved = TRUE), url_path)
  }
  if (!missing(`file`)) {
    url_path <- gsub("\\{file\\}", utils::URLencode(as.character(`file`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Get a file
#' @description Get the details of a file in the bucket
#' @param bucket.name  character
#' @param file  character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  - `file`: Name of the file
#'   - `size`: Size of the file
#'   - `time_created`: The time that the file was created
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::files_get(
#'    bucket.name, file
#' )
#' 
#' # Or provide directly
#' result <- ubiops::files_get(
#'    bucket.name, file,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
files_get <- function(bucket.name, file,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`bucket.name`)) {
    stop("Missing required parameter `bucket.name`.")
  }
  if (missing(`file`)) {
    stop("Missing required parameter `file`.")
  }
  
  url_path <- "/projects/{project_name}/buckets/{bucket_name}/files/{file}"
  if (!missing(`bucket.name`)) {
    url_path <- gsub("\\{bucket_name\\}", utils::URLencode(as.character(`bucket.name`), reserved = TRUE), url_path)
  }
  if (!missing(`file`)) {
    url_path <- gsub("\\{file\\}", utils::URLencode(as.character(`file`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List files
#' @description List files in a bucket
#' @param bucket.name  character
#' @param prefix (optional) character
#' @param delimiter (optional) character
#' @param continuation.token (optional) character
#' @param limit (optional) integer
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A dictionary containing the details of files and prefixes in the bucket
#'   - `continuation_token`: Next token to get the next set of files
#'   - `files`: A list of dictionaries containing the details of the files. It contains the file name ('file'), size of the file ('size') and the creation time of the file ('time_created').
#'   - `prefixes`: A list of directories
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::files_list(
#'    bucket.name,
#'    prefix = NULL, delimiter = NULL, continuation.token = NULL, limit = NULL
#' )
#' 
#' # Or provide directly
#' result <- ubiops::files_list(
#'    bucket.name,
#'    prefix = NULL, delimiter = NULL, continuation.token = NULL, limit = NULL, 
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
files_list <- function(bucket.name, prefix=NULL, delimiter=NULL, continuation.token=NULL, limit=NULL,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`bucket.name`)) {
    stop("Missing required parameter `bucket.name`.")
  }
  query_params['prefix'] <- prefix
  query_params['delimiter'] <- delimiter
  query_params['continuation_token'] <- continuation.token
  query_params['limit'] <- limit
  
  url_path <- "/projects/{project_name}/buckets/{bucket_name}/files"
  if (!missing(`bucket.name`)) {
    url_path <- gsub("\\{bucket_name\\}", utils::URLencode(as.character(`bucket.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Upload a file
#' @description Generate a signed url to upload a file. Request body should be an empty dictionary.
#' @param bucket.name  character
#' @param file  character
#' @param data (optional) list(key = "value")
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  - `url`: A url which can be used to upload the file to bucket. Make a PUT request to this url with the file content to upload the file.
#'   - `provider`: Provider of the bucket where the file will be uploaded
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::files_upload(
#'    bucket.name, file,
#'    data = NULL
#' )
#' 
#' # Or provide directly
#' result <- ubiops::files_upload(
#'    bucket.name, file,
#'    data = NULL, 
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
files_upload <- function(bucket.name, file, data=NULL,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`bucket.name`)) {
    stop("Missing required parameter `bucket.name`.")
  }
  if (missing(`file`)) {
    stop("Missing required parameter `file`.")
  }
  
  if (!missing(`data`) && !is.null(`data`)) {
    body <- rjson::toJSON(data)
  } else {
    body <- NULL
  }
  url_path <- "/projects/{project_name}/buckets/{bucket_name}/files/{file}"
  if (!missing(`bucket.name`)) {
    url_path <- gsub("\\{bucket_name\\}", utils::URLencode(as.character(`bucket.name`), reserved = TRUE), url_path)
  }
  if (!missing(`file`)) {
    url_path <- gsub("\\{file\\}", utils::URLencode(as.character(`file`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "POST", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}
