# UbiOps
#
# Client Library to interact with the UbiOps API.
#
# UbiOps API version: v2.1
# Generated by custom generator based on: https://openapi-generator.tech

# Metrics operations


#' @title Create metrics
#' @description Create a custom metric. The name must start with *custom.*.
#' @param data  named list of: [ name, description (optional), metric_type, unit (optional), labels (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the created metric
#'   - `id`: Unique identifier for the metric
#'   - `name`: Name of the metric
#'   - `description`: Description of the metric
#'   - `creation_date`: The date when the metric was created
#'   - `last_updated`: The date when the metric was last updated
#'   - `custom`: A boolean indicating whether the metric is custom
#'   - `metric_type`: Type of the metric
#'   - `unit`: Unit of the metric
#'   - `labels`: A list of labels that can be used to get data points containing the metric
#' @examples
#' \dontrun{
#' data <- list(
#'  name = "name",
#'  description = "description",  # (optional)
#'  metric_type = "metric_type",
#'  unit = "unit",  # (optional)
#'  labels = list("value-1", "value-2")  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::metrics_create(
#'    data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::metrics_create(
#'    data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
metrics_create <- function(data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}/metrics"

  api.response <- call_api(url_path, "POST", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Delete metric
#' @description Delete a metric. Only custom metrics can be deleted.
#' @param metric.name  character
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' ubiops::metrics_delete(
#'    metric.name
#' )
#' 
#' # Or provide directly
#' ubiops::metrics_delete(
#'    metric.name,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
metrics_delete <- function(metric.name,  ...){
  query_params <- list()

  if (missing(`metric.name`)) {
    stop("Missing required parameter `metric.name`.")
  }
  
  url_path <- "/projects/{project_name}/metrics/{metric_name}"
  if (!missing(`metric.name`)) {
    url_path <- gsub("\\{metric_name\\}", utils::URLencode(as.character(`metric.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "DELETE", NULL, query_params, ...)
  return(invisible(NULL))
}


#' @title Get metric
#' @description Retrieve details of a metric
#' @param metric.name  character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of a metric
#'   - `id`: Unique identifier for the metric
#'   - `name`: Name of the metric
#'   - `description`: Description of the metric
#'   - `creation_date`: The date when the metric was created
#'   - `last_updated`: The date when the metric was last updated
#'   - `custom`: A boolean indicating whether the metric is custom
#'   - `metric_type`: Type of the metric
#'   - `unit`: Unit of the metric
#'   - `labels`: A list of labels that can be used to get data points containing the metric
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::metrics_get(
#'    metric.name
#' )
#' 
#' # Or provide directly
#' result <- ubiops::metrics_get(
#'    metric.name,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
metrics_get <- function(metric.name,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`metric.name`)) {
    stop("Missing required parameter `metric.name`.")
  }
  
  url_path <- "/projects/{project_name}/metrics/{metric_name}"
  if (!missing(`metric.name`)) {
    url_path <- gsub("\\{metric_name\\}", utils::URLencode(as.character(`metric.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List metrics
#' @description List available metrics in the project
#' @param custom (optional) character ("true"|"false")
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list of details of metrics
#'   - `id`: Unique identifier for the metric
#'   - `name`: Name of the metric
#'   - `description`: Description of the metric
#'   - `creation_date`: The date when the metric was created
#'   - `last_updated`: The date when the metric was last updated
#'   - `custom`: A boolean indicating whether the metric is custom
#'   - `metric_type`: Type of the metric
#'   - `unit`: Unit of the metric
#'   - `labels`: A list of labels that can be used to get data points containing the metric
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::metrics_list(
#'    
#'    custom = NULL
#' )
#' 
#' # Or provide directly
#' result <- ubiops::metrics_list(
#'    
#'    custom = NULL, 
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
metrics_list <- function(custom=NULL,  preload_content=TRUE, ...){
  query_params <- list()

  query_params['custom'] <- custom
  
  url_path <- "/projects/{project_name}/metrics"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Update metric
#' @description Update a metric. Only custom metrics can be updated.
#' @param metric.name  character
#' @param data  named list of: [ name (optional), description (optional), unit (optional), labels (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the updated metric
#'   - `id`: Unique identifier for the metric
#'   - `name`: Name of the metric
#'   - `description`: Description of the metric
#'   - `creation_date`: The date when the metric was created
#'   - `last_updated`: The date when the metric was last updated
#'   - `custom`: A boolean indicating whether the metric is custom
#'   - `metric_type`: Type of the metric
#'   - `unit`: Unit of the metric
#'   - `labels`: A list of labels that can be used to get data points containing the metric
#' @examples
#' \dontrun{
#' data <- list(
#'  name = "name",  # (optional)
#'  description = "description",  # (optional)
#'  unit = "unit",  # (optional)
#'  labels = list("value-1", "value-2")  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::metrics_update(
#'    metric.name, data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::metrics_update(
#'    metric.name, data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
metrics_update <- function(metric.name, data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`metric.name`)) {
    stop("Missing required parameter `metric.name`.")
  }
  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}/metrics/{metric_name}"
  if (!missing(`metric.name`)) {
    url_path <- gsub("\\{metric_name\\}", utils::URLencode(as.character(`metric.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "PATCH", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Aggregate metric data
#' @description Aggregate metric data for given date, metrics and labels. Only data up to 2 minutes ago is accepted.
#' @param data  named list of: [ metric, labels (optional), data ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#' @examples
#' \dontrun{
#' data <- list(
#'  metric = "metric",
#'  labels = list(key = "value"),  # (optional)
#'  data = list(  # (optional)
#'    list(
#'      date = date,
#'      value = 0
#'    )
#'  )
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::time_series_data_aggregate(
#'    data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::time_series_data_aggregate(
#'    data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
time_series_data_aggregate <- function(data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}/time-series/aggregate"

  api.response <- call_api(url_path, "POST", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Create metric data
#' @description Insert data points for a metric. Multiple metrics for different types is supported.
#' @param data  named list of: [ metric, labels (optional), data ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#' @examples
#' \dontrun{
#' data <- list(
#'  metric = "metric",
#'  labels = list(key = "value"),  # (optional)
#'  data = list(  # (optional)
#'    list(
#'      date = date,
#'      value = 0
#'    )
#'  )
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::time_series_data_create(
#'    data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::time_series_data_create(
#'    data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
time_series_data_create <- function(data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}/time-series/data"

  api.response <- call_api(url_path, "POST", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List time series data
#' @description List data points for a metric  Available metrics for deployments: - `deployments.requests`: Number of requests to a deployment version - `deployments.failed_requests`: Number of failed requests to a deployment version - `deployments.request_duration`: Average time in seconds for a deployment request to complete - `deployments.input_volume`: Volume of incoming data in bytes - `deployments.output_volume`: Volume of outgoing data in bytes - `deployments.network_in`: Volume of inbound data traffic in bytes - `deployments.network_out`: Volume of outbound data traffic in bytes - `deployments.express_queue_size`: Average number of queued express requests - `deployments.batch_queue_size`: Average number of queued batch requests - `deployments.express_queue_time`: Average time in seconds for an express request to start processing - `deployments.batch_queue_time`: Average time in seconds for a batch request to start processing - `deployments.memory_utilization`: Average memory used during a request - `deployments.instances`: Number of active deployment instances - `deployments.credits`: Usage of credits, calculated by multiplying the credit rate of a deployment instance type by the number of hours the deployments are running  Available metrics for pipelines: - `pipelines.requests`: Number of requests to a pipeline version - `pipelines.failed_requests`: Number of failed requests to a pipeline version - `pipelines.request_duration`: Average time in seconds for a pipeline request to complete - `pipelines.input_volume`: Volume of incoming data in bytes - `pipelines.output_volume`: Volume of outgoing data in bytes - `pipelines.object_requests`: Number of object requests in a pipeline version - `pipelines.object_failed_requests`: Number of failed object requests in a pipeline version
#' @param metric (optional) character
#' @param start.date (optional) character
#' @param end.date (optional) character
#' @param aggregation.period (optional) integer
#' @param labels (optional) character - Example: "label1:value1,label2:value2"
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  - `metric`: Name of the metric
#'   - `metric_type`: Type of the metric
#'   - `unit`: Unit of the metric
#'   - `start_date`: Start date for metric data points
#'   - `end_date`: End date for metric data points
#'   - `aggregation_period`: Time period in seconds in which data points are grouped
#'   - `labels`: Labels to filter on data points
#'   - `data`: A list of dictionaries containing the data points
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::time_series_data_list(
#'    
#'    metric = NULL, start.date = NULL, end.date = NULL, aggregation.period = NULL, labels = NULL
#' )
#' 
#' # Or provide directly
#' result <- ubiops::time_series_data_list(
#'    
#'    metric = NULL, start.date = NULL, end.date = NULL, aggregation.period = NULL, labels = NULL, 
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
time_series_data_list <- function(metric=NULL, start.date=NULL, end.date=NULL, aggregation.period=NULL, labels=NULL,  preload_content=TRUE, ...){
  query_params <- list()

  query_params['metric'] <- metric
  query_params['start_date'] <- start.date
  query_params['end_date'] <- end.date
  query_params['aggregation_period'] <- aggregation.period
  query_params['labels'] <- labels
  
  url_path <- "/projects/{project_name}/time-series/data"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Delete time series
#' @description Delete a time series
#' @param time.series.id  character
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' ubiops::time_series_delete(
#'    time.series.id
#' )
#' 
#' # Or provide directly
#' ubiops::time_series_delete(
#'    time.series.id,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
time_series_delete <- function(time.series.id,  ...){
  query_params <- list()

  if (missing(`time.series.id`)) {
    stop("Missing required parameter `time.series.id`.")
  }
  
  url_path <- "/projects/{project_name}/time-series/{time_series_id}"
  if (!missing(`time.series.id`)) {
    url_path <- gsub("\\{time_series_id\\}", utils::URLencode(as.character(`time.series.id`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "DELETE", NULL, query_params, ...)
  return(invisible(NULL))
}


#' @title Search time series
#' @description Search through time series
#' @param metric (optional) character
#' @param labels (optional) character - Example: "label1:value1,label2:value2"
#' @param custom (optional) character ("true"|"false")
#' @param exact.match (optional) character ("true"|"false")
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list of time series
#'   - `metric`: Name of the metric
#'   - `labels`: Labels that the time series has
#'   - `resolution`: Metric resolution in seconds
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::time_series_search(
#'    
#'    metric = NULL, labels = NULL, custom = NULL, exact.match = NULL
#' )
#' 
#' # Or provide directly
#' result <- ubiops::time_series_search(
#'    
#'    metric = NULL, labels = NULL, custom = NULL, exact.match = NULL, 
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
time_series_search <- function(metric=NULL, labels=NULL, custom=NULL, exact.match=NULL,  preload_content=TRUE, ...){
  query_params <- list()

  query_params['metric'] <- metric
  query_params['labels'] <- labels
  query_params['custom'] <- custom
  query_params['exact_match'] <- exact.match
  
  url_path <- "/projects/{project_name}/time-series/search"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}
