# UbiOps
#
# Client Library to interact with the UbiOps API.
#
# UbiOps API version: v2.1
# Generated by custom generator based on: https://openapi-generator.tech

# Organizations operations


#' @title Add a user to an organization
#' @description Add a user to an organization as admin or normal user. The user making the request must be admin of the organization. The user can later be assigned roles in the projects defined in the scope the organization, such as project-admin, project-viewer etc.
#' @param organization.name  character
#' @param data  named list of: [ email, admin (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the added user
#'   - `id`: Unique identifier for the user (UUID) 
#'   - `email`: Email of the user 
#'   - `name`: Name of the user 
#'   - `surname`: Surname of the user 
#'   - `admin`: Boolean value indicating whether the user is an admin of the organization or not
#' @examples
#' \dontrun{
#' data <- list(
#'  email = "email",
#'  admin = FALSE  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::organization_users_create(
#'    organization.name, data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::organization_users_create(
#'    organization.name, data,
#'    UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
organization_users_create <- function(organization.name, data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`organization.name`)) {
    stop("Missing required parameter `organization.name`.")
  }
  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/organizations/{organization_name}/users"
  if (!missing(`organization.name`)) {
    url_path <- gsub("\\{organization_name\\}", utils::URLencode(as.character(`organization.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "POST", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Delete a user from an organization
#' @description Delete a user from an organization. The user making the request must be admin of the organization. It is not possible to delete the last admin of an organization.  **When a user is deleted from an organization, all his roles from all projects defined in the scope of the organization are also deleted.**
#' @param organization.name  character
#' @param user.id  character
#' @param ...
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' ubiops::organization_users_delete(
#'    organization.name, user.id
#' )
#' 
#' # Or provide directly
#' ubiops::organization_users_delete(
#'    organization.name, user.id,
#'    UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
organization_users_delete <- function(organization.name, user.id,  ...){
  query_params <- list()

  if (missing(`organization.name`)) {
    stop("Missing required parameter `organization.name`.")
  }
  if (missing(`user.id`)) {
    stop("Missing required parameter `user.id`.")
  }
  
  url_path <- "/organizations/{organization_name}/users/{user_id}"
  if (!missing(`organization.name`)) {
    url_path <- gsub("\\{organization_name\\}", utils::URLencode(as.character(`organization.name`), reserved = TRUE), url_path)
  }
  if (!missing(`user.id`)) {
    url_path <- gsub("\\{user_id\\}", utils::URLencode(as.character(`user.id`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "DELETE", NULL, query_params, ...)
  return(invisible(NULL))
}


#' @title Get details of a user in an organization
#' @description Get the details of a user in an organization. The user making the request must be admin of the organization.
#' @param organization.name  character
#' @param user.id  character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the user
#'   - `id`: Unique identifier for the user (UUID) 
#'   - `email`: Email of the user 
#'   - `name`: Name of the user 
#'   - `surname`: Surname of the user 
#'   - `admin`: Boolean value indicating whether the user is an admin of the organization or not
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::organization_users_get(
#'    organization.name, user.id
#' )
#' 
#' # Or provide directly
#' result <- ubiops::organization_users_get(
#'    organization.name, user.id,
#'    UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
organization_users_get <- function(organization.name, user.id,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`organization.name`)) {
    stop("Missing required parameter `organization.name`.")
  }
  if (missing(`user.id`)) {
    stop("Missing required parameter `user.id`.")
  }
  
  url_path <- "/organizations/{organization_name}/users/{user_id}"
  if (!missing(`organization.name`)) {
    url_path <- gsub("\\{organization_name\\}", utils::URLencode(as.character(`organization.name`), reserved = TRUE), url_path)
  }
  if (!missing(`user.id`)) {
    url_path <- gsub("\\{user_id\\}", utils::URLencode(as.character(`user.id`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List the users in an organization
#' @description List users and their details in an organization
#' @param organization.name  character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  List of details of users
#'   - `id`: Unique identifier for the user (UUID) 
#'   - `email`: Email of the user 
#'   - `name`: Name of the user 
#'   - `surname`: Surname of the user 
#'   - `admin`: Boolean value indicating whether the user is an admin of the organization or not
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::organization_users_list(
#'    organization.name
#' )
#' 
#' # Or provide directly
#' result <- ubiops::organization_users_list(
#'    organization.name,
#'    UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
organization_users_list <- function(organization.name,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`organization.name`)) {
    stop("Missing required parameter `organization.name`.")
  }
  
  url_path <- "/organizations/{organization_name}/users"
  if (!missing(`organization.name`)) {
    url_path <- gsub("\\{organization_name\\}", utils::URLencode(as.character(`organization.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Update details of a user in an organization
#' @description Update the admin status of a user in an organization. The user making the request must be admin of the organization. It is not possible to change the last admin of an organization to a regular user.
#' @param organization.name  character
#' @param user.id  character
#' @param data  named list of: [ admin (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the user
#'   - `id`: Unique identifier for the user (UUID) 
#'   - `email`: Email of the user 
#'   - `name`: Name of the user 
#'   - `surname`: Surname of the user 
#'   - `admin`: Boolean value indicating whether the user is an admin of the organization or not
#' @examples
#' \dontrun{
#' data <- list(
#'  admin = FALSE  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::organization_users_update(
#'    organization.name, user.id, data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::organization_users_update(
#'    organization.name, user.id, data,
#'    UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
organization_users_update <- function(organization.name, user.id, data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`organization.name`)) {
    stop("Missing required parameter `organization.name`.")
  }
  if (missing(`user.id`)) {
    stop("Missing required parameter `user.id`.")
  }
  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/organizations/{organization_name}/users/{user_id}"
  if (!missing(`organization.name`)) {
    url_path <- gsub("\\{organization_name\\}", utils::URLencode(as.character(`organization.name`), reserved = TRUE), url_path)
  }
  if (!missing(`user.id`)) {
    url_path <- gsub("\\{user_id\\}", utils::URLencode(as.character(`user.id`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "PATCH", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Create organizations
#' @description Create a new organization. When a user creates an organization, s/he will automatically become an organization admin.
#' @param data  named list of: [ name, subscription, subscription_end_date (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the created organization
#'   - `id`: Unique identifier for the organization (UUID) 
#'   - `name`: Name of the organization 
#'   - `creation_date`: Date and time the organization was created
#' @examples
#' \dontrun{
#' data <- list(
#'  name = "name",
#'  subscription = "subscription",
#'  subscription_end_date = subscription_end_date  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::organizations_create(
#'    data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::organizations_create(
#'    data,
#'    UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
organizations_create <- function(data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/organizations"
  api.response <- call_api(url_path, "POST", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Get details of an organization
#' @description Get the details of an organization
#' @param organization.name  character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the organization
#'   - `id`: Unique identifier for the organization (UUID) 
#'   - `name`: Name of the organization 
#'   - `creation_date`: Time the organization was created 
#'   - `subscription`: Name of the subscription of the organization 
#'   - `subscription_self_service`: Boolean indicating if the organization subscription is self service
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::organizations_get(
#'    organization.name
#' )
#' 
#' # Or provide directly
#' result <- ubiops::organizations_get(
#'    organization.name,
#'    UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
organizations_get <- function(organization.name,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`organization.name`)) {
    stop("Missing required parameter `organization.name`.")
  }
  
  url_path <- "/organizations/{organization_name}"
  if (!missing(`organization.name`)) {
    url_path <- gsub("\\{organization_name\\}", utils::URLencode(as.character(`organization.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List organizations
#' @description List all organizations where the user making the request is a member
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list of details of the organizations
#'   - `id`: Unique identifier for the organization (UUID) 
#'   - `name`: Name of the organization 
#'   - `creation_date`: Date and time the organization was created
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::organizations_list(
#'    
#' )
#' 
#' # Or provide directly
#' result <- ubiops::organizations_list(
#'    UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
organizations_list <- function( preload_content=TRUE, ...){
  query_params <- list()

  
  url_path <- "/organizations"
  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Get resource usage
#' @description List the total number of resources used by this organization
#' @param organization.name  character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list containing the number of
#'   - projects 
#'   - users 
#'   - deployments 
#'   - deployment_versions 
#'   - pipelines 
#'   - pipeline_versions 
#'   currently used by the organization.
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::organizations_resource_usage(
#'    organization.name
#' )
#' 
#' # Or provide directly
#' result <- ubiops::organizations_resource_usage(
#'    organization.name,
#'    UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
organizations_resource_usage <- function(organization.name,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`organization.name`)) {
    stop("Missing required parameter `organization.name`.")
  }
  
  url_path <- "/organizations/{organization_name}/resources"
  if (!missing(`organization.name`)) {
    url_path <- gsub("\\{organization_name\\}", utils::URLencode(as.character(`organization.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Update details of an organization
#' @description Update an organization. The user making the request must be admin of the organization. Users are able to update the name of the organization, but changes to the subscription can only be done by Dutch Analytics. To delete the end date of the current subscription, give the 'subscription_end_date' parameter with value null.
#' @param organization.name  character
#' @param data  named list of: [ name (optional), subscription (optional), subscription_end_date (optional), subscription_start_date (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the organization
#'   - `id`: Unique identifier for the organization (UUID) 
#'   - `name`: Name of the organization 
#'   - `creation_date`: Time the organization was created 
#'   - `subscription`: Name of the subscription
#' @examples
#' \dontrun{
#' data <- list(
#'  name = "name",  # (optional)
#'  subscription = "subscription",  # (optional)
#'  subscription_end_date = subscription_end_date,  # (optional)
#'  subscription_start_date = subscription_start_date  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::organizations_update(
#'    organization.name, data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::organizations_update(
#'    organization.name, data,
#'    UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
organizations_update <- function(organization.name, data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`organization.name`)) {
    stop("Missing required parameter `organization.name`.")
  }
  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/organizations/{organization_name}"
  if (!missing(`organization.name`)) {
    url_path <- gsub("\\{organization_name\\}", utils::URLencode(as.character(`organization.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "PATCH", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Get organization usage
#' @description Get resource usage for the organization. It contains **the details of each metric aggregated per month.**
#' @param organization.name  character
#' @param start.date (optional) character
#' @param end.date (optional) character
#' @param interval (optional) character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  - `metric`: Metric name
#'   - `object_type`: Type of object the metric was measured for (deployment_version or pipeline_version)
#'   - `usage`: an array of objects each containing the following:
#'     - `start_date`: Timestamp denoting the start of the current subscription period or the provided date
#'     - `end_date`: Timestamp denoting the end of the current subscription period or the provided date
#'     - `value`: Aggregated metric value for the given unit over the given month
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::organizations_usage_get(
#'    organization.name,
#'    start.date = NULL, end.date = NULL, interval = 'month'
#' )
#' 
#' # Or provide directly
#' result <- ubiops::organizations_usage_get(
#'    organization.name,
#'    start.date = NULL, end.date = NULL, interval = 'month', 
#'    UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
organizations_usage_get <- function(organization.name, start.date=NULL, end.date=NULL, interval='month',  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`organization.name`)) {
    stop("Missing required parameter `organization.name`.")
  }
  query_params['start_date'] <- start.date
  query_params['end_date'] <- end.date
  query_params['interval'] <- interval
  
  url_path <- "/organizations/{organization_name}/usage"
  if (!missing(`organization.name`)) {
    url_path <- gsub("\\{organization_name\\}", utils::URLencode(as.character(`organization.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}
