# UbiOps
#
# Client Library to interact with the UbiOps API.
#
# UbiOps API version: v2.1
# Generated by custom generator based on: https://openapi-generator.tech

# Projects operations


#' @title List instance types
#' @description Get list of available deployment instance types for a project
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the instance type
#'   - `id`: Unique identifier for the instance type (UUID)
#'   - `name`: Name of the deployment instance type
#'   - `display_name`: Readable name of the deployment instance type
#'   - `memory_allocation`: Integer indicating memory allocation for this instance type (Mi)
#'   - `cpu_allocation`: Float indicating vCPU allocation for this instance type
#'   - `gpu_allocation`: Integer indicating number of GPU cores for this instance type
#'   - `storage_allocation`: Integer indicating the maximum storage that can be used by this instance type (MB)
#'   - `credit_rate`: Credits used per hour for this instance type
#'   - `dedicated_node`: A boolean indicating whether an entire node is dedicated to this instance type
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::instance_types_list(
#'    
#' )
#' 
#' # Or provide directly
#' result <- ubiops::instance_types_list(
#'    
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
instance_types_list <- function( preload_content=TRUE, ...){
  query_params <- list()

  
  url_path <- "/projects/{project_name}/instance-types"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List audit events in a project
#' @description List all audit events in a project including all objects
#' @param action (optional) character
#' @param limit (optional) integer
#' @param offset (optional) integer
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list of details of the audit events in the project
#'   - `id`: Unique identifier for the audit event (UUID)
#'   - `date`: The date when the action was performed
#'   - `action`: Type of action. It can be one of: create, update, delete, info. *info* action denotes that the action does not fall into create, update or delete categories.
#'   - `user`: Email of the user who performed the action
#'   - `event`: Description of the event
#'   - `object_type`: Type of the object on which the action was performed
#'   - `object_name`: Name of the object on which the action was performed. If the object is deleted at the time of listing audit events, this field is empty.
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::project_audit_events_list(
#'    
#'    action = NULL, limit = NULL, offset = NULL
#' )
#' 
#' # Or provide directly
#' result <- ubiops::project_audit_events_list(
#'    
#'    action = NULL, limit = NULL, offset = NULL, 
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
project_audit_events_list <- function(action=NULL, limit=NULL, offset=NULL,  preload_content=TRUE, ...){
  query_params <- list()

  query_params['action'] <- action
  query_params['limit'] <- limit
  query_params['offset'] <- offset
  
  url_path <- "/projects/{project_name}/audit"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Create project environment variable
#' @description Create an environment variable for the project. This variable will be inherited by all deployments in this project.
#' @param data  named list of: [ name, value, secret ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list of variables described by the following fields:
#'   - `id`: Unique identifier for the environment variable
#'   - `name`: Variable name
#'   - `value`: Variable value (will be null for secret variables)
#'   - `secret`: Boolean that indicates if this variable contains sensitive information
#' @examples
#' \dontrun{
#' data <- list(
#'  name = "name",
#'  value = "value",
#'  secret = FALSE
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::project_environment_variables_create(
#'    data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::project_environment_variables_create(
#'    data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
project_environment_variables_create <- function(data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}/environment-variables"

  api.response <- call_api(url_path, "POST", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Delete project environment variable
#' @description Delete an environment variable of the project
#' @param id  character
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' ubiops::project_environment_variables_delete(
#'    id
#' )
#' 
#' # Or provide directly
#' ubiops::project_environment_variables_delete(
#'    id,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
project_environment_variables_delete <- function(id,  ...){
  query_params <- list()

  if (missing(`id`)) {
    stop("Missing required parameter `id`.")
  }
  
  url_path <- "/projects/{project_name}/environment-variables/{id}"
  if (!missing(`id`)) {
    url_path <- gsub("\\{id\\}", utils::URLencode(as.character(`id`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "DELETE", NULL, query_params, ...)
  return(invisible(NULL))
}


#' @title Get project environment variable
#' @description Retrieve details of a project environment variable.
#' @param id  character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list of variables described by the following fields:
#'   - `id`: Unique identifier for the environment variable
#'   - `name`: Variable name
#'   - `value`: Variable value (will be null for secret variables)
#'   - `secret`: Boolean that indicates if this variable contains sensitive information
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::project_environment_variables_get(
#'    id
#' )
#' 
#' # Or provide directly
#' result <- ubiops::project_environment_variables_get(
#'    id,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
project_environment_variables_get <- function(id,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`id`)) {
    stop("Missing required parameter `id`.")
  }
  
  url_path <- "/projects/{project_name}/environment-variables/{id}"
  if (!missing(`id`)) {
    url_path <- gsub("\\{id\\}", utils::URLencode(as.character(`id`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List project environment variables
#' @description List the environment variables defined for the project. These are the variables that are inherited by all deployments in this project.
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list of variables described by the following fields:
#'   - `id`: Unique identifier for the environment variable
#'   - `name`: Variable name
#'   - `value`: Variable value (will be null for secret variables)
#'   - `secret`: Boolean that indicates if this variable contains sensitive information
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::project_environment_variables_list(
#'    
#' )
#' 
#' # Or provide directly
#' result <- ubiops::project_environment_variables_list(
#'    
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
project_environment_variables_list <- function( preload_content=TRUE, ...){
  query_params <- list()

  
  url_path <- "/projects/{project_name}/environment-variables"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Update project environment variable
#' @description Update an environment variable for the projects
#' @param id  character
#' @param data  named list of: [ name, value, secret ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list of variables described by the following fields:
#'   - `id`: Unique identifier for the environment variable
#'   - `name`: Variable name
#'   - `value`: Variable value (will be null for secret variables)
#'   - `secret`: Boolean that indicates if this variable contains sensitive information
#' @examples
#' \dontrun{
#' data <- list(
#'  name = "name",
#'  value = "value",
#'  secret = FALSE
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::project_environment_variables_update(
#'    id, data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::project_environment_variables_update(
#'    id, data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
project_environment_variables_update <- function(id, data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`id`)) {
    stop("Missing required parameter `id`.")
  }
  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}/environment-variables/{id}"
  if (!missing(`id`)) {
    url_path <- gsub("\\{id\\}", utils::URLencode(as.character(`id`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "PATCH", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List requests in project
#' @description List the deployment/pipeline requests of the given project
#' @param object.type  character
#' @param status (optional) character
#' @param success (optional) character ("true"|"false")
#' @param limit (optional) integer
#' @param offset (optional) integer
#' @param sort (optional) character
#' @param pipeline (optional) character ("true"|"false")
#' @param request.schedule (optional) character
#' @param start.date (optional) character
#' @param end.date (optional) character
#' @param search.id (optional) character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list of dictionaries containing the metadata of the deployment/pipeline requests with the following fields:
#'   - `id`: The UUID of the object
#'   - `deployment`: Name of the deployment the request was made to (Optional: in case it's a deployment request. Else NULL)
#'   - `pipeline`: Name of the pipeline the request was made to (Optional: in case it's a pipeline request. Else NULL)
#'   - `version`: Name of the version the request was made to
#'   - `status`: Status of the request
#'   - `success`: A boolean value that indicates whether the deployment/pipeline request was successful. NULL if the request is not yet finished.
#'   - `time_created`: Server time that the request was made (current time)
#'   - `time_started`: Server time that the processing of the request was started
#'   - `time_completed`: Server time that the processing of the request was completed
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::project_requests_list(
#'    object.type,
#'    status = NULL, success = NULL, limit = NULL, offset = NULL, sort = NULL, pipeline = NULL, request.schedule = NULL, start.date = NULL, end.date = NULL, search.id = NULL
#' )
#' 
#' # Or provide directly
#' result <- ubiops::project_requests_list(
#'    object.type,
#'    status = NULL, success = NULL, limit = NULL, offset = NULL, sort = NULL, pipeline = NULL, request.schedule = NULL, start.date = NULL, end.date = NULL, search.id = NULL, 
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
project_requests_list <- function(object.type, status=NULL, success=NULL, limit=NULL, offset=NULL, sort=NULL, pipeline=NULL, request.schedule=NULL, start.date=NULL, end.date=NULL, search.id=NULL,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`object.type`)) {
    stop("Missing required parameter `object.type`.")
  }
  query_params['object_type'] <- object.type
  query_params['status'] <- status
  query_params['success'] <- success
  query_params['limit'] <- limit
  query_params['offset'] <- offset
  query_params['sort'] <- sort
  query_params['pipeline'] <- pipeline
  query_params['request_schedule'] <- request.schedule
  query_params['start_date'] <- start.date
  query_params['end_date'] <- end.date
  query_params['search_id'] <- search.id
  
  url_path <- "/projects/{project_name}/requests"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Add user to a project
#' @description Add a user to a project. The user making the request must be admin of the organization. The user can later be assigned roles in the project, such as project-admin, project-viewer etc.
#' @param data  named list of: [ user_id ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the added user
#'   - `id`: Unique identifier for the user (UUID)
#'   - `email`: Email of the user
#'   - `name`: Name of the user
#'   - `surname`: Surname of the user
#' @examples
#' \dontrun{
#' data <- list(
#'  user_id = "user_id"
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::project_users_create(
#'    data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::project_users_create(
#'    data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
project_users_create <- function(data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}/users"

  api.response <- call_api(url_path, "POST", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Delete user from a project
#' @description Delete a user from a project. The user making the request must be admin of the organization.  **When a user is deleted from a project, all his roles defined in the scope of the project are also deleted.**
#' @param user.id  character
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' ubiops::project_users_delete(
#'    user.id
#' )
#' 
#' # Or provide directly
#' ubiops::project_users_delete(
#'    user.id,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
project_users_delete <- function(user.id,  ...){
  query_params <- list()

  if (missing(`user.id`)) {
    stop("Missing required parameter `user.id`.")
  }
  
  url_path <- "/projects/{project_name}/users/{user_id}"
  if (!missing(`user.id`)) {
    url_path <- gsub("\\{user_id\\}", utils::URLencode(as.character(`user.id`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "DELETE", NULL, query_params, ...)
  return(invisible(NULL))
}


#' @title Get user in a project
#' @description Get the details of a user in a project. The user making the request must also be a project user.
#' @param user.id  character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the user
#'   - `id`: Unique identifier for the user (UUID)
#'   - `email`: Email of the user
#'   - `name`: Name of the user
#'   - `surname`: Surname of the user
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::project_users_get(
#'    user.id
#' )
#' 
#' # Or provide directly
#' result <- ubiops::project_users_get(
#'    user.id,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
project_users_get <- function(user.id,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`user.id`)) {
    stop("Missing required parameter `user.id`.")
  }
  
  url_path <- "/projects/{project_name}/users/{user_id}"
  if (!missing(`user.id`)) {
    url_path <- gsub("\\{user_id\\}", utils::URLencode(as.character(`user.id`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List users in a project
#' @description List users and their details in a project. The user making the request must also be a project user.
#' @param user.type (optional) character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  List of users
#'   - `id`: Unique identifier for the user (UUID)
#'   - `email`: Email of the user
#'   - `name`: Name of the user
#'   - `surname`: Surname of the user
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::project_users_list(
#'    
#'    user.type = NULL
#' )
#' 
#' # Or provide directly
#' result <- ubiops::project_users_list(
#'    
#'    user.type = NULL, 
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
project_users_list <- function(user.type=NULL,  preload_content=TRUE, ...){
  query_params <- list()

  query_params['user_type'] <- user.type
  
  url_path <- "/projects/{project_name}/users"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Create projects
#' @description Create a new project with the provided name.  **Only the organization admins have permission to make this request.** When a new project is created, the current organization admins are assigned project-admin role for the created project.
#' @param data  named list of: [ name, organization_name, advanced_permissions (optional), credits (optional), cors_origins (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the created project
#'   - `id`: Unique identifier for the project (UUID)
#'   - `name`: Name of the project
#'   - `creation_date`: Time the project was created
#'   - `advanced_permissions`: A boolean to enable/disable advanced permissions for the project
#'   - `organization_name`: Name of the organization in which the project is created
#'   - `credits`: Maximum usage of credits, calculated by multiplying the credit rate of a deployment instance type by the number of hours they are running
#'   - `suspended`: A boolean indicating whether the project is suspended due to going over the credits limit
#'   - `suspended_reason`: Description explaining why the project is suspended
#'   - `cors_origins`: List of origins from which the requests are allowed for the project
#' @examples
#' \dontrun{
#' data <- list(
#'  name = "name",
#'  organization_name = "organization_name",
#'  advanced_permissions = FALSE,  # (optional)
#'  credits = 0,  # (optional)
#'  cors_origins = list("value-1", "value-2")  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::projects_create(
#'    data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::projects_create(
#'    data,
#'    UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
projects_create <- function(data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects"
  api.response <- call_api(url_path, "POST", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Delete a project
#' @description Delete a project. The user making the request must have appropriate permissions.  **When project is deleted, all the deployments and pipelines defined in it are also deleted.**
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' ubiops::projects_delete(
#'    
#' )
#' 
#' # Or provide directly
#' ubiops::projects_delete(
#'    
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
projects_delete <- function( ...){
  query_params <- list()

  
  url_path <- "/projects/{project_name}"

  api.response <- call_api(url_path, "DELETE", NULL, query_params, ...)
  return(invisible(NULL))
}


#' @title Get details of a project
#' @description Get the details of a single project. The user making the request must have appropriate permissions.
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of a project
#'   - `id`: Unique identifier for the project (UUID)
#'   - `name`: Name of the project
#'   - `creation_date`: Time the project was created
#'   - `advanced_permissions`: A boolean to enable/disable advanced permissions for the project
#'   - `organization_name`: Name of the organization in which the project is created
#'   - `credits`: Maximum usage of credits, calculated by multiplying the credit rate of a deployment instance type by the number of hours they are running
#'   - `suspended`: A boolean indicating whether the project is suspended due to going over the credits limit
#'   - `suspended_reason`: Description explaining why the project is suspended
#'   - `cors_origins`: List of origins from which the requests are allowed for the project
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::projects_get(
#'    
#' )
#' 
#' # Or provide directly
#' result <- ubiops::projects_get(
#'    
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
projects_get <- function( preload_content=TRUE, ...){
  query_params <- list()

  
  url_path <- "/projects/{project_name}"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List projects
#' @description List all projects to which the user making request has access. The projects in organizations to which the user belongs are shown.
#' @param organization (optional) character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list of details of the projects
#'   - `id`: Unique identifier for the project (UUID)
#'   - `name`: Name of the project
#'   - `creation_date`: Time the project was created
#'   - `advanced_permissions`: A boolean to enable/disable advanced permissions for the project
#'   - `organization_name`: Name of the organization in which the project is created
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::projects_list(
#'    
#'    organization = NULL
#' )
#' 
#' # Or provide directly
#' result <- ubiops::projects_list(
#'    organization = NULL, 
#'    UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
projects_list <- function(organization=NULL,  preload_content=TRUE, ...){
  query_params <- list()

  query_params['organization'] <- organization
  
  url_path <- "/projects"
  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List logs for a project
#' @description Retrieve the logs of all objects in a project, including deployments, pipelines and requests. Using filters you can filter the logs on the objects and information of your choice.
#' @param data (optional) named list of: [ filters (optional), date_range (optional), date (optional), id (optional), limit (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list of log details
#'   - `id`: Unique UUID of the log line
#'   - `log`: Log line text
#'   - `date`: Time the log line was created
#'   The following fields will be returned on response if they are set for the log line:
#'   - `deployment_name`:  The deployment which the log is related to
#'   - `deployment_version`:  The deployment version which the log is related to
#'   - `deployment_version_revision_id`: The UUID of the deployment version revision
#'   - `environment_name`:  The environment which the log is related to
#'   - `environment_build_id`: The UUID of the environment build
#'   - `pipeline_name`: The pipeline which the log is related to
#'   - `pipeline_version`: The pipeline version which the log is related to
#'   - `pipeline_object_name`: The pipeline object which the log is related to
#'   - `deployment_request_id`:  The deployment request the log is related to
#'   - `pipeline_request_id`:  The pipeline request the log is related to
#'   - `system`:  Whether the log was generated by the system (true / false)
#'   - `level`: The level of the log (info / error)
#' @examples
#' \dontrun{
#' data <- list(
#'  filters = list(key = "value"),  # (optional)
#'  date_range = 0,  # (optional)
#'  date = "date",  # (optional)
#'  id = "id",  # (optional)
#'  limit = 0  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::projects_log_list(
#'    
#'    data = NULL
#' )
#' 
#' # Or provide directly
#' result <- ubiops::projects_log_list(
#'    
#'    data = NULL, 
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
projects_log_list <- function(data=NULL,  preload_content=TRUE, ...){
  query_params <- list()

  
  if (!missing(`data`) && !is.null(`data`)) {
    body <- rjson::toJSON(data)
  } else {
    body <- NULL
  }
  url_path <- "/projects/{project_name}/logs"

  api.response <- call_api(url_path, "POST", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List resource usage of a project
#' @description List the total number of resources used in a project
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list containing the number of
#'   - deployments
#'   - deployment_versions
#'   - pipelines
#'   - pipeline_versions
#'   - buckets
#'   - environments
#'   currently defined in the project.
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::projects_resource_usage(
#'    
#' )
#' 
#' # Or provide directly
#' result <- ubiops::projects_resource_usage(
#'    
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
projects_resource_usage <- function( preload_content=TRUE, ...){
  query_params <- list()

  
  url_path <- "/projects/{project_name}/resources"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Update a project
#' @description Update the name of a single project. The user making the request must have appropriate permissions.
#' @param data  named list of: [ name (optional), advanced_permissions (optional), credits (optional), suspend (optional), cors_origins (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of a project
#'   - `id`: Unique identifier for the project (UUID)
#'   - `name`: Name of the project
#'   - `creation_date`: Time the project was created
#'   - `advanced_permissions`: A boolean to enable/disable advanced permissions for the project
#'   - `organization_name`: Name of the organization in which the project is created
#'   - `credits`: Maximum usage of credits, calculated by multiplying the credit rate of a deployment instance type by the number of hours they are running
#'   - `suspended`: A boolean indicating whether the project is suspended due to going over the credits limit
#'   - `suspended_reason`: Description explaining why the project is suspended
#'   - `cors_origins`: List of origins from which the requests are allowed for the project
#' @examples
#' \dontrun{
#' data <- list(
#'  name = "name",  # (optional)
#'  advanced_permissions = FALSE,  # (optional)
#'  credits = 0,  # (optional)
#'  suspend = FALSE,  # (optional)
#'  cors_origins = list("value-1", "value-2")  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::projects_update(
#'    data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::projects_update(
#'    data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
projects_update <- function(data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}"

  api.response <- call_api(url_path, "PATCH", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Get resource usage
#' @description Get credits usage for the project
#' @param start.date (optional) character
#' @param end.date (optional) character
#' @param interval (optional) character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  - `interval`: Interval for the usage data
#'   - `data_project`: A list of dictionaries containing the project usage for the given date range
#'   - `data_deployments`: A list of dictionaries containing the usage of each deployment in the project for the given date range
#'   - `data_deployments_deleted`: A list of dictionaries containing the usage corresponds to deleted deployments in the project for the given date range
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::projects_usage_get(
#'    
#'    start.date = NULL, end.date = NULL, interval = 'month'
#' )
#' 
#' # Or provide directly
#' result <- ubiops::projects_usage_get(
#'    
#'    start.date = NULL, end.date = NULL, interval = 'month', 
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
projects_usage_get <- function(start.date=NULL, end.date=NULL, interval='month',  preload_content=TRUE, ...){
  query_params <- list()

  query_params['start_date'] <- start.date
  query_params['end_date'] <- end.date
  query_params['interval'] <- interval
  
  url_path <- "/projects/{project_name}/usage"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List quotas
#' @description List the quotas defined for a project. Project members can see quotas.
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  - `resource`: The resource for the quota
#'   - `quota`: Limit of how much the resource can be used in the project
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::quotas_list(
#'    
#' )
#' 
#' # Or provide directly
#' result <- ubiops::quotas_list(
#'    
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
quotas_list <- function( preload_content=TRUE, ...){
  query_params <- list()

  
  url_path <- "/projects/{project_name}/quotas"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}
