# UbiOps
#
# Client Library to interact with the UbiOps API.
#
# UbiOps API version: v2.1
# Generated by custom generator based on: https://openapi-generator.tech

# RequestSchedules operations


#' @title Create request schedules
#' @description Create a new request schedule with the provided name
#' @param data  named list of: [ name, object_type, object_name, version (optional), schedule, request_data (optional), batch (optional), timeout (optional), enabled (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the created request schedule
#'   - `name`: Name of the request 
#'   - `object_type`: Type of object for which the request is made 
#'   - `object_name`: Name of deployment/pipeline for which the request schedule is made 
#'    
#'   - `schedule`: Schedule in crontab format 
#'   - `version`: Name of version for which the request schedule is made 
#'   - `request_data`: Input data for the request schedule 
#'   - `batch`: Boolean value indicating whether the requests will be performed as batch requests (true) or as direct requests (false) 
#'   - `timeout`: Timeout in seconds 
#'   - `enabled`: Boolean value indicating whether the request schedule is enabled or disabled 
#'   - `creation_date`: The date when the request schedule was created
#' @examples
#' \dontrun{
#' data <- list(
#'  name = "name",
#'  object_type = "object_type",
#'  object_name = "object_name",
#'  version = "version",  # (optional)
#'  schedule = "schedule",
#'  request_data = list(key = "value"),  # (optional)
#'  batch = FALSE,  # (optional)
#'  timeout = 0,  # (optional)
#'  enabled = FALSE  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::request_schedules_create(
#'    data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::request_schedules_create(
#'    data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
request_schedules_create <- function(data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}/schedules"

  api.response <- call_api(url_path, "POST", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Delete a request schedule
#' @description Delete the request schedule from the project.   If you want to temporarily disable a request schedule, update the request with `enabled` set to False.
#' @param schedule.name  character
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' ubiops::request_schedules_delete(
#'    schedule.name
#' )
#' 
#' # Or provide directly
#' ubiops::request_schedules_delete(
#'    schedule.name,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
request_schedules_delete <- function(schedule.name,  ...){
  query_params <- list()

  if (missing(`schedule.name`)) {
    stop("Missing required parameter `schedule.name`.")
  }
  
  url_path <- "/projects/{project_name}/schedules/{schedule_name}"
  if (!missing(`schedule.name`)) {
    url_path <- gsub("\\{schedule_name\\}", utils::URLencode(as.character(`schedule.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "DELETE", NULL, query_params, ...)
  return(invisible(NULL))
}


#' @title Get details of a request schedule
#' @description Retrieve details of a single request schedule
#' @param schedule.name  character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of a request schedule
#'   - `name`: Name of the request 
#'   - `object_type`: Type of object for which the request is made 
#'   - `object_name`: Name of deployment/pipeline for which the request is made 
#'    
#'   - `schedule`: Schedule in crontab format 
#'   - `version`: Name of version for which the request schedule is made 
#'   - `request_data`: Input data for the request schedule 
#'   - `batch`: Boolean value indicating whether the requests will be performed as batch requests (true) or as direct requests (false) 
#'   - `timeout`: Timeout in seconds 
#'   - `enabled`: Boolean value indicating whether the request schedule is enabled or disabled 
#'   - `creation_date`: The date when the request schedule was created
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::request_schedules_get(
#'    schedule.name
#' )
#' 
#' # Or provide directly
#' result <- ubiops::request_schedules_get(
#'    schedule.name,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
request_schedules_get <- function(schedule.name,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`schedule.name`)) {
    stop("Missing required parameter `schedule.name`.")
  }
  
  url_path <- "/projects/{project_name}/schedules/{schedule_name}"
  if (!missing(`schedule.name`)) {
    url_path <- gsub("\\{schedule_name\\}", utils::URLencode(as.character(`schedule.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List request schedules
#' @description List the request schedules in a project. The user has to have 'requests.list' permission on either 'deployments.versions' or 'pipelines.versions' to list the request schedules.
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list of details of all request schedules in a project
#'   - `name`: Name of the request 
#'   - `object_type`: Type of object for which the request is made 
#'   - `object_name`: Name of deployment/pipeline for which the request is made 
#'    
#'   - `schedule`: Schedule in crontab format 
#'   - `version`: Name of version for which the request schedule is made  
#'   - `request_data`: Input data for the request schedule 
#'   - `batch`: Boolean value indicating whether the requests will be performed as batch requests (true) or as direct requests (false) 
#'   - `timeout`: Timeout in seconds 
#'   - `enabled`: Boolean value indicating whether the request schedule is enabled or disabled 
#'   - `creation_date`: The date when the request schedule was created
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::request_schedules_list(
#'    
#' )
#' 
#' # Or provide directly
#' result <- ubiops::request_schedules_list(
#'    
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
request_schedules_list <- function( preload_content=TRUE, ...){
  query_params <- list()

  
  url_path <- "/projects/{project_name}/schedules"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Update a request schedule
#' @description Update a request schedule in a project. Create permissions on the object are necessary for this action.
#' @param schedule.name  character
#' @param data  named list of: [ name (optional), schedule (optional), request_data (optional), batch (optional), timeout (optional), enabled (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the updated request schedule
#'   - `name`: Name of the request 
#'   - `object_type`: Type of object for which the request is made 
#'   - `object_name`: Name of deployment/pipeline for which the request is made 
#'    
#'   - `schedule`: Schedule in crontab format 
#'   - `version`: Name of version for which the request schedule is made 
#'   - `request_data`: Input data for the request schedule 
#'   - `batch`: Boolean value indicating whether the requests will be performed as batch requests (true) or as direct requests (false) 
#'   - `timeout`: Timeout in seconds 
#'   - `enabled`: Boolean value indicating whether the request schedule is enabled or disabled 
#'   - `creation_date`: The date when the request schedule was created
#' @examples
#' \dontrun{
#' data <- list(
#'  name = "name",  # (optional)
#'  schedule = "schedule",  # (optional)
#'  request_data = list(key = "value"),  # (optional)
#'  batch = FALSE,  # (optional)
#'  timeout = 0,  # (optional)
#'  enabled = FALSE  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::request_schedules_update(
#'    schedule.name, data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::request_schedules_update(
#'    schedule.name, data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
request_schedules_update <- function(schedule.name, data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`schedule.name`)) {
    stop("Missing required parameter `schedule.name`.")
  }
  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}/schedules/{schedule_name}"
  if (!missing(`schedule.name`)) {
    url_path <- gsub("\\{schedule_name\\}", utils::URLencode(as.character(`schedule.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "PATCH", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}
