# UbiOps
#
# Client Library to interact with the UbiOps API.
#
# UbiOps API version: v2.1
# Generated by custom generator based on: https://openapi-generator.tech

# Webhooks operations


#' @title Create webhook tests
#' @description Test a webhook
#' @param data  named list of: [ object_type, object_name, version (optional), url, headers (optional), event, timeout (optional), retry (optional), include_result (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the test
#'   - `id`: Unique identifier for the test (UUID)
#'   - `status`: Status of the test. It can be one of the following: 'pending', 'completed' or 'failed'.
#'   - `error_message`: An error message explaining why the test has failed
#' @examples
#' \dontrun{
#' data <- list(
#'  object_type = "object_type",
#'  object_name = "object_name",
#'  version = "version",  # (optional)
#'  url = "url",
#'  headers = list(  # (optional)
#'    list(
#'      key = "key",
#'      value = "value",
#'      protected = FALSE
#'    )
#'  ),
#'  event = "event",
#'  timeout = 0,  # (optional)
#'  retry = FALSE,  # (optional)
#'  include_result = FALSE  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::webhook_tests_create(
#'    data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::webhook_tests_create(
#'    data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
webhook_tests_create <- function(data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}/webhooks-tests"

  api.response <- call_api(url_path, "POST", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Get webhook test
#' @description Retrieve details of a webhook test in a project
#' @param test.id  character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of a test
#'   - `id`: Unique identifier for the test (UUID)
#'   - `status`: Status of the test. It can be one of the following: 'pending', 'completed' or 'failed'.
#'   - `error_message`: An error message explaining why the test has failed
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::webhook_tests_get(
#'    test.id
#' )
#' 
#' # Or provide directly
#' result <- ubiops::webhook_tests_get(
#'    test.id,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
webhook_tests_get <- function(test.id,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`test.id`)) {
    stop("Missing required parameter `test.id`.")
  }
  
  url_path <- "/projects/{project_name}/webhooks-tests/{test_id}"
  if (!missing(`test.id`)) {
    url_path <- gsub("\\{test_id\\}", utils::URLencode(as.character(`test.id`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Create webhooks
#' @description Create a webhook
#' @param data  named list of: [ name, object_type, object_name, version (optional), url, headers (optional), event, description (optional), labels (optional), timeout (optional), enabled (optional), retry (optional), include_result (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of the created webhook
#'   - `id`: Unique identifier for the webhook (UUID)
#'   - `name`: Name of the webhook
#'   - `url`: Callback url to send event payloads to
#'   - `headers`: Request headers to use when calling the webhook
#'   - `object_type`: Type of object for which the webhook is created
#'   - `object_name`: Name of deployment or pipeline for which the webhook is created
#'   - `version`: Name of deployment/pipeline version for which the webhook is created
#'   - `description`: Description of the webhook
#'   - `labels`: Dictionary containing key/value pairs where key indicates the label and value is the corresponding value of that label
#'   - `event`: Event that triggers the webhook
#'   - `timeout`: Timeout in seconds on the call to webhook
#'   - `enabled`: Boolean value indicating whether the webhook is enabled or disabled
#'   - `retry`: Boolean value indicating whether the calls to webhook should be retried if they fail
#' @examples
#' \dontrun{
#' data <- list(
#'  name = "name",
#'  object_type = "object_type",
#'  object_name = "object_name",
#'  version = "version",  # (optional)
#'  url = "url",
#'  headers = list(  # (optional)
#'    list(
#'      key = "key",
#'      value = "value",
#'      protected = FALSE
#'    )
#'  ),
#'  event = "event",
#'  description = "description",  # (optional)
#'  labels = list(key = "value"),  # (optional)
#'  timeout = 0,  # (optional)
#'  enabled = FALSE,  # (optional)
#'  retry = FALSE,  # (optional)
#'  include_result = FALSE  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::webhooks_create(
#'    data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::webhooks_create(
#'    data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
webhooks_create <- function(data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}/webhooks"

  api.response <- call_api(url_path, "POST", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Delete a webhook
#' @description Delete a webhook
#' @param webhook.name  character
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' ubiops::webhooks_delete(
#'    webhook.name
#' )
#' 
#' # Or provide directly
#' ubiops::webhooks_delete(
#'    webhook.name,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
webhooks_delete <- function(webhook.name,  ...){
  query_params <- list()

  if (missing(`webhook.name`)) {
    stop("Missing required parameter `webhook.name`.")
  }
  
  url_path <- "/projects/{project_name}/webhooks/{webhook_name}"
  if (!missing(`webhook.name`)) {
    url_path <- gsub("\\{webhook_name\\}", utils::URLencode(as.character(`webhook.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "DELETE", NULL, query_params, ...)
  return(invisible(NULL))
}


#' @title Get webhook
#' @description Retrieve details of a webhook in a project
#' @param webhook.name  character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of a webhook
#'   - `id`: Unique identifier for the webhook (UUID)
#'   - `name`: Name of the webhook
#'   - `url`: Callback url to send event payloads to
#'   - `headers`: Request headers to use when calling the webhook
#'   - `object_type`: Type of object for which the webhook is created
#'   - `object_name`: Name of deployment or pipeline for which the webhook is created
#'   - `version`: Name of deployment/pipeline version for which the webhook is created
#'   - `description`: Description of the webhook
#'   - `labels`: Dictionary containing key/value pairs where key indicates the label and value is the corresponding value of that label
#'   - `event`: Event that triggers the webhook
#'   - `timeout`: Timeout in seconds on the call to webhook
#'   - `enabled`: Boolean value indicating whether the webhook is enabled or disabled
#'   - `retry`: Boolean value indicating whether the calls to webhook should be retried if they fail
#'   - `include_result`: Boolean indicating whether the result of a request should be included in the webhook call
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::webhooks_get(
#'    webhook.name
#' )
#' 
#' # Or provide directly
#' result <- ubiops::webhooks_get(
#'    webhook.name,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
webhooks_get <- function(webhook.name,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`webhook.name`)) {
    stop("Missing required parameter `webhook.name`.")
  }
  
  url_path <- "/projects/{project_name}/webhooks/{webhook_name}"
  if (!missing(`webhook.name`)) {
    url_path <- gsub("\\{webhook_name\\}", utils::URLencode(as.character(`webhook.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title List webhooks
#' @description List the webhooks in a project
#' @param labels (optional) character - Example: "label1:value1,label2:value2"
#' @param object.type (optional) character
#' @param event (optional) character
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  A list of details of the webhooks in the project
#'   - `id`: Unique identifier for the webhook (UUID)
#'   - `name`: Name of the webhook
#'   - `url`: Callback url to send event payloads to
#'   - `headers`: Request headers to use when calling the webhook
#'   - `object_type`: Type of object for which the webhook is created
#'   - `object_name`: Name of deployment or pipeline for which the webhook is created
#'   - `version`: Name of deployment/pipeline version for which the webhook is created
#'   - `description`: Description of the webhook
#'   - `labels`: Dictionary containing key/value pairs where key indicates the label and value is the corresponding value of that label
#'   - `event`: Event that triggers the webhook
#'   - `timeout`: Timeout in seconds on the call to webhook
#'   - `enabled`: Boolean value indicating whether the webhook is enabled or disabled
#'   - `retry`: Boolean value indicating whether the calls to webhook should be retried if they fail
#'   - `include_result`: Boolean indicating whether the result of a request should be included in the webhook call
#' @examples
#' \dontrun{
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::webhooks_list(
#'    
#'    labels = NULL, object.type = NULL, event = NULL
#' )
#' 
#' # Or provide directly
#' result <- ubiops::webhooks_list(
#'    
#'    labels = NULL, object.type = NULL, event = NULL, 
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
webhooks_list <- function(labels=NULL, object.type=NULL, event=NULL,  preload_content=TRUE, ...){
  query_params <- list()

  query_params['labels'] <- labels
  query_params['object_type'] <- object.type
  query_params['event'] <- event
  
  url_path <- "/projects/{project_name}/webhooks"

  api.response <- call_api(url_path, "GET", NULL, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}


#' @title Update a webhook
#' @description Update a webhook
#' @param webhook.name  character
#' @param data  named list of: [ name (optional), url (optional), headers (optional), event (optional), description (optional), labels (optional), timeout (optional), enabled (optional), retry (optional), include_result (optional) ]
#' @param preload_content (optional) Whether the API response should be preloaded. When TRUE the JSON response string is parsed to an R object. When FALSE, unprocessed API response object is returned. - Default = TRUE
#' @param ...
#'  UBIOPS_PROJECT (system environment variable) UbiOps project name
#'  UBIOPS_API_TOKEN (system environment variable) Token to connect to UbiOps API
#'  UBIOPS_API_URL (optional - system environment variable) UbiOps API url - Default = "https://api.ubiops.com/v2.1"
#'  UBIOPS_TIMEOUT (optional - system environment variable) Maximum request timeout to connect to UbiOps API - Default = NA
#'  UBIOPS_DEFAULT_HEADERS (optional - system environment variable) Default headers to pass to UbiOps API, formatted like "header1:value1,header2:value2" - Default = ""
#' @return Response from the API
#'  Details of a webhook
#'   - `id`: Unique identifier for the webhook (UUID)
#'   - `name`: Name of the webhook
#'   - `url`: Callback url to send event payloads to
#'   - `headers`: Request headers to use when calling the webhook
#'   - `object_type`: Type of object for which the webhook is created
#'   - `object_name`: Name of deployment or pipeline for which the webhook is created
#'   - `version`: Name of deployment/pipeline version for which the webhook is created
#'   - `description`: Description of the webhook
#'   - `labels`: Dictionary containing key/value pairs where key indicates the label and value is the corresponding value of that label
#'   - `event`: Event that triggers the webhook
#'   - `timeout`: Timeout in seconds on the call to webhook
#'   - `enabled`: Boolean value indicating whether the webhook is enabled or disabled
#'   - `retry`: Boolean value indicating whether the calls to webhook should be retried if they fail
#'   - `include_result`: Boolean indicating whether the result of a request should be included in the webhook call
#' @examples
#' \dontrun{
#' data <- list(
#'  name = "name",  # (optional)
#'  url = "url",  # (optional)
#'  headers = list(  # (optional)
#'    list(
#'      key = "key",
#'      value = "value",
#'      protected = FALSE
#'    )
#'  ),
#'  event = "event",  # (optional)
#'  description = "description",  # (optional)
#'  labels = list(key = "value"),  # (optional)
#'  timeout = 0,  # (optional)
#'  enabled = FALSE,  # (optional)
#'  retry = FALSE,  # (optional)
#'  include_result = FALSE  # (optional)
#' )
#'
#' # Use environment variables
#' Sys.setenv("UBIOPS_PROJECT" = "YOUR PROJECT NAME")
#' Sys.setenv("UBIOPS_API_TOKEN" = "YOUR API TOKEN")
#' result <- ubiops::webhooks_update(
#'    webhook.name, data
#' )
#' 
#' # Or provide directly
#' result <- ubiops::webhooks_update(
#'    webhook.name, data,
#'    UBIOPS_PROJECT = "YOUR PROJECT NAME", UBIOPS_API_TOKEN = "YOUR API TOKEN"
#' )
#' 
#' print(result)
#' 
#' # The default API url is https://api.ubiops.com/v2.1
#' # Want to use a different API url?
#' # Provide `UBIOPS_API_URL`, either directly or as environment variable.
#' }
#' @export
webhooks_update <- function(webhook.name, data,  preload_content=TRUE, ...){
  query_params <- list()

  if (missing(`webhook.name`)) {
    stop("Missing required parameter `webhook.name`.")
  }
  if (missing(`data`)) {
    stop("Missing required parameter `data`.")
  }
  
  body <- rjson::toJSON(data)
  
  url_path <- "/projects/{project_name}/webhooks/{webhook_name}"
  if (!missing(`webhook.name`)) {
    url_path <- gsub("\\{webhook_name\\}", utils::URLencode(as.character(`webhook.name`), reserved = TRUE), url_path)
  }

  api.response <- call_api(url_path, "PATCH", body, query_params, ...)
  if (preload_content) {
    deserializedRespObj <- tryCatch(
      deserialize(api.response),
      error = function(e){
        stop("Failed to deserialize response")
      }
    )

  } else {
    ApiResponse$new(api.response)
  }
}
